#!/bin/sh

export PHP_VERSION=71

echo "${APP_NAME} going up"
export CONTAINER_NAME_PREFIX=driblyp
export COMPOSE_PROJECT_NAME="Dribly"
export APPLICATION=../


echo "Building ${CONTAINER_NAME_PREFIX}"


docker-compose --project-name="Dribly" up -d web-nginx web-mariadb
echo "All done. upping ${APP_NAME}  Hope it worked"
